# Generated by Django 4.2.10 on 2025-03-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ShoppyGo", "0004_alter_userprofile_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
