# Generated by Django 4.2.10 on 2025-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ShoppyGo", "0006_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pprofile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
