# Generated by Django 4.2.10 on 2025-03-22 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ShoppyGo", "0007_customuser_pprofile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="pprofile_image",
            new_name="profile_image",
        ),
    ]
